apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"elvis:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"elvis\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-03-21T20:34:39Z"
  generation: 2
  labels:
    app: elvis
    app.kubernetes.io/component: elvis
    app.kubernetes.io/instance: elvis
  name: elvis
  namespace: ggosla-design-container
  resourceVersion: "33717992"
  selfLink: /apis/apps/v1/namespaces/ggosla-design-container/deployments/elvis
  uid: aa2d7bc3-0362-4ed2-beb4-e1aaa711a3c1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: elvis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: elvis
    spec:
      containers:
      - image: quay.io/ssmith_sdg/do288-hello-java@sha256:af5ac255815212311f6b7564033672ebe694d18e39ed72ff11c2ce6aeaf924a9
        imagePullPolicy: IfNotPresent
        name: elvis
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-03-21T20:34:48Z"
    lastUpdateTime: "2022-03-21T20:34:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-21T20:34:40Z"
    lastUpdateTime: "2022-03-21T20:34:48Z"
    message: ReplicaSet "elvis-6575b6bff7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
